## WARNING ##
# The following configuration code is architected by DevOps experts or under the supervision of DevOps experts, which can make or break Automated jobs like Build and Deployments. Accordingly, we at PeerXP insist that you do not attempt to change or re-create any activity in this code.


# Please send an email to support@peerxp.com if you have any requests.
## WARNING ##

include:
    remote: https://config.vegaops.com/arkaenergy/marketing20portal/vegaops-glci.yml

